spring.application.name=resource-sharing

spring.datasource.url=jdbc:mysql://localhost:3306/community_resource_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shivshantsyco@gmail.com
spring.mail.password=vnxqfiruwlyoltwc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.main.allow-bean-definition-overriding=true

# VERY IMPORTANT (you already set correctly)
spring.jpa.open-in-view=false

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

razorpay.key.id=rzp_test_S6xwztnBjI813H
razorpay.key.secret=LhaSOJHU26LCmDexNMQHN5J1

# === ADD THIS LINE TO SERVE UPLOADED FILES ===
spring.web.resources.static-locations=classpath:/static/,file:uploads/







# vnxq firu wlyo ltwc

# key_id    rzp_test_S6xwztnBjI813H
# key_secret  LhaSOJHU26LCmDexNMQHN5J1


